# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dt_format', models.IntegerField(choices=[(0, 'DD/MM/YYYY HH:mm')], default=0, verbose_name='Date / time format')),
            ],
        ),
    ]
