# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicash_core', '0007_auto_20170506_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='created_date',
            new_name='dt_stamp',
        ),
    ]
