"""
Django settings for minicash project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

import dj_database_url


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
APP_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
BASE_DIR = os.path.abspath(os.path.join(APP_ROOT, '../../'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


ALLOWED_HOSTS = []

# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


DATABASES = {
    'default': dj_database_url.config('MINICASH_DB_URL'),
}

DEBUG = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'django_filters',
    'django_js_utils',
    'djmoney',
    'rest_framework',

    'minicash.app.apps.AppConfig',
    'minicash.auth.apps.AuthConfig',
    'minicash.core.apps.CoreConfig',
    'minicash.frontend.apps.FrontendConfig',
]

LANGUAGE_CODE = 'en-us'

LOGIN_REDIRECT_URL = '/'

LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    'ORDERING_PARAM': 'sort_by',
}

ROOT_URLCONF = 'minicash.app.urls'


SECRET_KEY = os.environ['MINICASH_SECRET_KEY']


SETTINGS_EXPORT = [
    'DEBUG',
]

STATIC_ROOT = os.path.join(APP_ROOT, 'staticfiles')
STATIC_URL = '/static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
            ],
        },
    },
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

WSGI_APPLICATION = 'minicash.app.wsgi.application'


# ========== Minicash-specific settings ========== #
# ================================================ #

MINICASH = {
    'AUTH_DEFAULT_BACKEND_DATETIME_FORMAT': '%d/%m/%Y %H:%M',
    'DEFAULT_CURRENCY': 'EUR',
    'DEFAULT_PAGINATOR_PAGE_SIZE': 20,
}




